{
 "title": "boatVSboat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "boat",
    "query": {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -3h) // o -1y per dati più vecchi\n  |> filter(fn: (r) => r._measurement == \"navigazione\")  // <-- qui specifichi il measurement\n  |> keep(columns: [\"boat\"])  // tieni solo il tag che ti interessa\n  |> distinct(column: \"boat\")  // prendi solo i valori unici"
    }
   },
   {
    "name": "boat2",
    "query": {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -3h) // o -1y per dati più vecchi\n  |> filter(fn: (r) => r._measurement == \"navigazione\")  // <-- qui specifichi il measurement\n  |> keep(columns: [\"boat\"])  // tieni solo il tag che ti interessa\n  |> distinct(column: \"boat\")  // prendi solo i valori unici"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -3m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    (r._field == \"latitude\" or r._field == \"longitude\") and\n    r.boat == \"${boat}\" and\n    r.opponent == \"${boat2}\"\n  )\n  |> aggregateWindow(every: 1s, fn: last)\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"boat\"])"
    },
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -3m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    (r._field == \"latitude\" or r._field == \"longitude\") and\n    r.boat == \"${boat2}\" and\n    r.opponent == \"${boat}\"\n  )\n  |> aggregateWindow(every: 1s, fn: last)\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> keep(columns: [\"_time\", \"latitude\", \"longitude\", \"boat\"])"
    }
   ]
  },
  {
   "title": "Velocità",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_speed\" and\n    r.boat == \"${boat}\" and\n    r.opponent == \"${boat2}\")\n\n"
    },
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_speed\" and\n    r.boat == \"${boat2}\" and\n    r.opponent == \"${boat}\")\n\n"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_true_wind_speed\" and\n    r.boat == \"${boat}\" and r.opponent == \"${boat2}\"\n    )\n\n      |> map(fn: (r) => ({ r with _field: \"Velocità vento ${boat}\" }))"
    },
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_true_wind_speed\" and\n    r.boat == \"${boat2}\" and r.opponent == \"${boat}\"\n    )\n\n      |> map(fn: (r) => ({ r with _field: \"Velocità vento ${boat2}\" }))"
    }
   ]
  },
  {
   "title": "Boat status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"is_foiling\" and\n    r.boat == \"${boat}\" and\n    r.opponent == \"${boat2}\")\n\n        |> map(fn: (r) => ({ r with _field: \"${boat}\" }))"
    },
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"is_foiling\" and\n    r.boat == \"${boat}\" and\n    r.opponent == \"${boat2}\")\n\n    |> map(fn: (r) => ({ r with _field: \"${boat2}\" }))"
    }
   ]
  },
  {
   "title": "Velocità",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_speed\" and\n    r.boat == \"${boat}\" and r.opponent == \"${boat2}\"\n    )\n\n      |> map(fn: (r) => ({ r with _field: \"Velocità ${boat}\" }))"
    },
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_speed\" and\n    r.boat == \"${boat2}\" and r.opponent == \"${boat}\"\n    )\n\n      |> map(fn: (r) => ({ r with _field: \"Velocità ${boat2}\" }))"
    }
   ]
  },
  {
   "title": "VMG",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_vmg\" and\n    r.boat == \"${boat}\" and r.opponent == \"${boat2}\"\n    )\n\n      |> map(fn: (r) => ({ r with _field: \"VMG ${boat}\" }))"
    },
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"avg_vmg\" and\n    r.boat == \"${boat2}\" and r.opponent == \"${boat}\"\n    )\n\n      |> map(fn: (r) => ({ r with _field: \"VMG ${boat2}\" }))"
    }
   ]
  },
  {
   "title": "Race status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"BoatvsBoat\" and\n    r._field == \"leg_number\" and\n    r.boat == \"${boat}\")"
    }
   ]
  }
 ]
}