{
 "title": "Navigazione",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "boat",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"Navigation\",\n  tag: \"boat\"\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"avg_true_wind_direction\" and\n    r.boat == \"${boat}\")\n  "
    }
   ]
  },
  {
   "title": "Heading",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"avg_heading\" and\n    r.boat == \"${boat}\")"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"avg_speed\" and\n    r.boat == \"${boat}\")"
    }
   ]
  },
  {
   "title": "TWS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"avg_true_wind_speed\" and\n    r.boat == \"${boat}\")\n\n"
    }
   ]
  },
  {
   "title": "VMG",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"avg_vmg\" and\n    r.boat == \"${boat}\")\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"avg_speed\" and\n    r.boat == \"${boat}\")\n  "
    }
   ]
  },
  {
   "title": "Race status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"leg\" and\n    r.boat == \"${boat}\")"
    }
   ]
  },
  {
   "title": "Boat status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Navigation\")\n  |> range(start: -1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"navigazione\" and\n    r._field == \"is_foiling\" and\n    r.boat == \"${boat}\")"
    }
   ]
  }
 ]
}