{
 "title": "prometeus L",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "kafka_in_message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(kafka_messages_in_per_sec)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "consumer repose time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_request_queue_time_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_prduce_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_produce_request_latency_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "task_manager_CPU_laod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load{host=\"172_18_0_6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "telegraf cpu Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}